[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "social-media-gif-downloader"
version = "1.0.0"
description = "A GUI application to download videos/GIFs from Twitter/X, Pinterest, and Instagram and convert them to GIFs"
authors = [
    {name = "ax2bboud", email = "contact@ax2bboud.com"},
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Multimedia :: Video :: Conversion",
]
dependencies = [
    "moviepy>=1.0.0",
    "customtkinter>=5.0.0",
]

[project.urls]
Homepage = "https://github.com/ax2bboud/social-media-gif-downloader"
Repository = "https://github.com/ax2bboud/social-media-gif-downloader"
Issues = "https://github.com/ax2bboud/social-media-gif-downloader/issues"

[project.scripts]
social-media-gif-downloader = "social_media_gif_downloader:main"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "pytest-cov",
    "pytest-xdist",
]

[tool.setuptools]
license-files = ["LICENSE"]
py-modules = ["social_media_gif_downloader"]