name: Version Bump

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run version bump
      id: bump
      run: |
        python scripts/version_manager.py bump
        NEW_VERSION=$(python scripts/version_manager.py get-current-version)
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git push
        git push --tags

    - name: Create pull request for release
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: bump version to ${{ steps.bump.outputs.new_version }}"
        title: "Release v${{ steps.bump.outputs.new_version }}"
        body: |
          This PR was automatically created to prepare for release v${{ steps.bump.outputs.new_version }}.

          ## Changes
          - Version bumped to ${{ steps.bump.outputs.new_version }}
          - Tag `v${{ steps.bump.outputs.new_version }}` created

          ## Next Steps
          - Review and merge this PR
          - The release workflow will automatically trigger on the tag push
        branch: release/v${{ steps.bump.outputs.new_version }}
        delete-branch: true